version: "3"

services:
  db:
    container_name: webapp_db_dev
    build:
      context: ./docker/db
    ports:
      - 3306:3306
    volumes:
      - laravel_db:/var/lib/mysql
    platform: linux/x86_64
  app:
    container_name: webapp_app_dev
    build:
      context: ./docker/app
    volumes:
      - ./src:/work/backend
    depends_on: ["db"]
  web:
    container_name: webapp_web_dev
    build:
      context: ./docker/web
    ports:
      - 80:80
    volumes:
      - ./src:/work/backend
    depends_on: ["app"]

volumes:
  laravel_db:
